### ISSUE TITLE
New TWBT decorations

### ISSUE THREAD

**Issue by Bltgn** [Bltgn/DF-succubus#58]
Meph prepared some special decorations to use with TWBT, I only have to fill the blanks in building_succubus.

TWBT: no custom building for name PENTAGRAM
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name ROOT
TWBT: no custom building for name TOTEM
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name CANDELABRA
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name DRAGON_ALTAR
TWBT: no custom building for name BRAZIER
TWBT: no custom building for name FIREPLACE
TWBT: no custom building for name ABACUS
TWBT: no custom building for name DICE
TWBT: no custom building for name TORTURE_RACK
TWBT: no custom building for name COFFIN
TWBT: no custom building for name SIGN
TWBT: no custom building for name SKULL
TWBT: no custom building for name TOMBSTONE
TWBT: no custom building for name CROSSED_SWORDS
TWBT: no custom building for name SKELETON
TWBT: no custom building for name HOURGLASS
TWBT: no custom building for name POTTED_PLANT_2_1_RED
TWBT: no custom building for name POTTED_PLANT_2_1_RED
TWBT: no custom building for name POTTED_PLANT_1_2_BUSH
TWBT: no custom building for name POTTED_PLANT_1_2_RED
TWBT: no custom building for name POTTED_PLANT_1_2_GREEN
TWBT: no custom building for name POTTED_PLANT_RED
TWBT: no custom building for name POTTED_PLANT_YELLOW
TWBT: no custom building for name POTTED_PLANT
TWBT: no custom building for name POTTED_PLANT_2_1_RED
TWBT: no custom building for name POTTED_PLANT_2_1_RED
TWBT: no custom building for name POTTED_PLANT_1_2_BUSH
TWBT: no custom building for name POTTED_PLANT_1_2_RED
TWBT: no custom building for name POTTED_PLANT_1_2_GREEN
TWBT: no custom building for name POTTED_PLANT_BLUE
TWBT: no custom building for name POTTED_PLANT_PASTEL
TWBT: no custom building for name POTTED_PLANT_DARK_GREEN

**Comment by Devduweb** [comment]
Must review items too for newer version and possibly workshops.

**Comment by Bltgn** [comment]
Closing this one as Meph added a lot of decorations in his tileset and the mod has been made compatible.
